# Generated by Django 4.2.7 on 2024-04-14 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatauthor', to=settings.AUTH_USER_MODEL),
        ),
    ]
