# Generated by Django 4.2.7 on 2024-04-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
