# Generated by Django 4.2.7 on 2024-05-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_alter_chatmodel_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
