# Generated by Django 4.2.1 on 2024-03-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Socialposts', '0002_tag_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='image',
        ),
    ]
